### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Dhivyaaj**

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
run auto-merge

**Comment by Dhivyaaj** [comment]
run merge

**Comment by Dhivyaaj** [comment]
run merge

**Comment by Dhivyaaj** [comment]
run merge

**Comment by Dhivyaaj** [comment]
run merge

**Comment by Dhivyaaj** [comment]
run merge

**Comment by Dhivyaaj** [comment]
run merge

**Comment by Dhivyaaj** [comment]
run auto-merge

**Comment by yograjshisode** [comment]
Closing test PR

**Pull request closed without merging**
