### PR TITLE
Auto updated assets for go models and clients eng

### PR DESCRIPTION
**Pull request by yograjshisode**

### CODE REVIEW

**Comment by yograjshisode** [comment]
run jenkins-go-sdk-ut

**Comment by Dhivyaaj** [comment]
run Go-SDK-UT

**Comment by Dhivyaaj** [comment]
run jenkins-go-sdk-ut

**Comment by Dhivyaaj** [comment]
run jenkins-go-sdk-ut

**Comment by Dhivyaaj** [comment]
run jenkins-go-sdk-ut

**Comment by yograjshisode** [comment]
run jenkins-go-sdk-ut

**Pull request merged**
