### PR TITLE
Av 32567 Vcrpy sdk unit tests

### PR DESCRIPTION
**Pull request by patilshrikant486**

### CODE REVIEW

**Comment by grastogi23** [comment]
this need to be rebased to 17.2.6

**Review by grastogi23 — CHANGES_REQUESTED** [review]
pl. rebase to 17.2.6

**Comment by patilshrikant486** [comment]
Done with rebase

**Review by grastogi23 — APPROVED** [review]

**Comment by grastogi23** [comment]
@patilshrikant486  it now has conflicts

**Comment by patilshrikant486** [comment]
Fixed conflicts

**Review by grastogi23 — APPROVED** [review]

**Pull request merged**
