### PR TITLE
Auto updated assets for python eng

### PR DESCRIPTION
**Pull request by yograjshisode**

### CODE REVIEW

**Comment by yograjshisode** [comment]
run jenkins-python-sdk-ut

**Comment by Dhivyaaj** [comment]
run jenkins-F5-migration-ut

**Comment by yograjshisode** [comment]
run jenkins-F5-migration-ut

**Comment by yograjshisode** [comment]
run jenkins-NS-migration-ut

**Comment by yograjshisode** [comment]
run jenkins-python-sdk-ut

**Comment by yograjshisode** [comment]
run jenkins-F5-migration-ut

**Review by chaitanyaavi — APPROVED** [review]

**Pull request merged**
