### PR TITLE
Rc clone vs dev

### PR DESCRIPTION
**Pull request by thebertster**
Based on a few customer use cases, added:
1. Handling SSO policies
2. SNI Parent/Child VS
3. Pool-member mapping
4. Optionally allow DataScripts to be re-used rather than cloned

Other changes:
1. Working directly with vsvip object rather than proxy vip object in VS
2. Auto-discover of "best" API version to use (optional)
3. Support ssl certs in admin tenant used by VS in non-admin tenant

### CODE REVIEW

**Comment by grastogi23** [comment]
Hi @rwhitt114,
Thanks for enhancing this. Given this is becoming very valuable and more complex it would be nice to have a unit test for it added.  Can you please create at least a simple unit tests for cloning with APIs mocked so we can include it in travis and better for long term maintainability.

thanks
Gaurav

**Review by grastogi23 — CHANGES_REQUESTED** [review]
pl. add unit tests.

**Comment by thebertster** [comment]
Hi @grastogi23 - I assume this was directed at me not @rwhitt114. Can you point me at examples of unit tests for this kind of thing - I'm not sure what to do. Thanks.

**Comment by grastogi23** [comment]
> Hi @grastogi23 - I assume this was directed at me not @rwhitt114. Can you point me at examples of unit tests for this kind of thing - I'm not sure what to do. Thanks.

https://github.com/avinetworks/sdk/tree/master/python/avi/sdk/test

**Review by grastogi23 — APPROVED** [review]

**Comment by grastogi23** [comment]
@thebertster please work with @chaitanyaavi  in India timezone. He will be able to guide you for unit test. Please also cherry-pick to 18.2.6

**Review by grastogi23 — APPROVED** [review]

**Pull request merged**
