### PR TITLE
Fix certificate verify failed at login

### PR DESCRIPTION
**Pull request by matthieugouel**
Hello, 

When I try to log into a controller via the Python SDK I have the following error : 

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='X.X.X.X', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))
``` 

I noticed that the `verify`method of the class `ApiSession` is never used and is not passed at the post call for the authentication. 

This modification fixes the problem for me. 

Best regards,
Matthieu.

### CODE REVIEW

**Review by grastogi23 — APPROVED** [review]

**Comment by matthieugouel** [comment]
Hello ! Any idea when this PR will be merged ?
Cheers,
Matthieu.

**Comment by grastogi23** [comment]
@matthieugouel we will look into it. Somehow this PR was lost as it was not assigned to any engineer explicitly.

**Comment by matthieugouel** [comment]
Thanks a lot ! 
Have a good day,
Matthieu.

**Comment by grastogi23** [comment]
@matthieugouel  the code sets the self.verify for the ApiSession. that should have automatically set it for the underlying session class. we will look into why this is not working.

**Comment by chaitanyaavi** [comment]
Taken care with latest release branch 18.1.5 hence closing this
https://github.com/avinetworks/sdk/pull/741

**Pull request closed without merging**
