### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Dhivyaaj**
test docs sdk

### CODE REVIEW

**Comment by Dhivyaaj** [comment]
auto-merge

**Comment by Dhivyaaj** [comment]
run auto-merge

**Comment by Dhivyaaj** [comment]
run auto-merge

**Comment by Dhivyaaj** [comment]
run auto-merge

**Comment by Dhivyaaj** [comment]
run auto-merge

**Comment by Dhivyaaj** [comment]
run auto-merge

**Comment by Dhivyaaj** [comment]
run auto-merge

**Comment by mayank-avinetworks** [comment]
Go SDK UT PASSED

**Comment by Dhivyaaj** [comment]
run auto-merge

**Comment by Dhivyaaj** [comment]
run auto-merge

**Pull request merged**
